export const EXPIRE_TOKEN_ERROR = "La sesión ha expirado";
export const ERROR_MESSAGE = "Oops! Something went wrong!";
export const PARISHES = [
  "Los Esteros",
  "Manta",
  "San Mateo",
  "Tarqui",
  "Eloy Alfaro",
  "San Lorenzo",
  "Santa Marianita",
];

export const initialStateCrop = {
  _id: "",
  name: "",
  description: "",
  image: "",
  scientificName: "",
  active: true,
  categoryId: "",
  beneficalNeighboursId: [],
  plaguesId: [],
  germinationTime: 0,
  harvestTime: 0,
  sowingSeason: "",
  solarLight: "",
  plantedAtHome: false,
  plotSize: 0,
  thermalFloor: "",
  transplantSoil: "",
  temperatureMax: 1,
  temperatureMin: 1,
  typeOfSoil: "",
  fertilisersId: [],
  harmfulNeighboursId: [],
  reproductionsId: [],
  submit: undefined,
};

export const initialCultiveData = {
  _id: "",
  name: "Cultivo 1",
  description: "Cultivo 1",
  image: "",
  scientificName: "Cultivus",
  active: true,
  categoryId: "665b95c17428ab24536a3469",
  beneficalNeighboursId: [
    { _id: "66648788effd6b1b35404d77" },
    { _id: "6664bfc7540b308daa43ec8d" },
  ],
  plaguesId: [{ _id: "66647092effd6b1b35404d6b" }],
  germinationTime: 20,
  harvestTime: 20,
  sowingSeason: "Verano",
  SolarLight: "Mucha",
  plantedAtHome: false,
  plotSize: 10,
  thermalFloor: "Caliente",
  typeOfSoil: "Humedo",
  fertilisersId: ["6664720eeffd6b1b35404d6e"],
  harmfulNeighboursId: [{ _id: "665ba9ab7428ab24536a346a" }],
  reproductionsId: ["66647501effd6b1b35404d72", "666470faeffd6b1b35404d6d"],
  transplantSoil: "Humedo",
  temperatureMax: 30,
  temperatureMin: 10,
};
